---
version: "2"

plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true

exclude_patterns:
  - package-lock.json
  - node_modules/
