# Header Menu
menu:
  Home: /
  Blog: /blog
  Sobre: /about

# Integrations
disqus_shortname: ramon-santos
google_analytics: UA-82053881-1
facebook_app_id: 122740845026539
twitter_id: ramonsantos_dev
g_plus: https://plus.google.com/+RamonSantosDev
facebook_user_id: CjHweHcsUQm
